spring:
  application:
    name: shopping
  datasource:
    url: jdbc:h2:tcp://localhost/~/shoppingking
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect